name: CI

on: [push]

jobs:
  build:
    name: Simple Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: git clone https://github.com/gibbets/CIDemo.git
      - name: Make Test
        run: |
          cd CIDemo
          make
          ls
          ./prog

        
            
